Table Entrees {
    id int [pk, increment]
     name varchar
    price number
}

Table Vegetables {
    id int [pk, increment]
    name varchar
    price number
}

Table SideDishes {
    id int [pk, increment]
    name varchar
    price number
}

Table Sales {
    id int [pk, increment]
    dish_id int [ref: > Entrees.id]
    vegetable_id int [ref: > Vegetables.id]
    side_dish_id int [ref: > SideDishes.id]
    total_price number
}
