Table Dish {
    id int [pk, increment]
    name varchar
    price number
}

Table Vegetable {
    id int [pk, increment]
    name varchar
    price number
}

Table SideDish {
    id int [pk, increment]
    name varchar
    price number
}

Table Sales {
    id int [pk, increment]
    dish_id int [ref: > Dish.id]
    vegetable_id int [ref: > Vegetable.id]
    side_dish_id int [ref: > SideDish.id]
    total_price number
}
